// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamVietManh_PH529888.Models;

#nullable disable

namespace PhamVietManh_PH529888.Migrations
{
    [DbContext(typeof(SanPhamDBContext))]
    [Migration("20240711080322_l1")]
    partial class l1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhamVietManh_PH529888.Models.SanPham", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            id = new Guid("11c1ad61-8d91-45fa-8468-facea4a98553"),
                            ImgURL = "...",
                            Name = "Hung",
                            SoLuong = 1
                        },
                        new
                        {
                            id = new Guid("b55131d0-625b-44b9-a108-426ba921a14a"),
                            ImgURL = "...",
                            Name = "Banh",
                            SoLuong = 9
                        },
                        new
                        {
                            id = new Guid("5ba990c1-6b03-4f24-92c0-bd497eafc665"),
                            ImgURL = "...",
                            Name = "Keo",
                            SoLuong = 5
                        },
                        new
                        {
                            id = new Guid("9cf0399c-8fab-4058-9c35-d412786da05c"),
                            ImgURL = "...",
                            Name = "Khoai",
                            SoLuong = 8
                        },
                        new
                        {
                            id = new Guid("d2f25cb8-0a15-4a3a-948b-2d55ef6d6b04"),
                            ImgURL = "...",
                            Name = "Dua hau",
                            SoLuong = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
